### ISSUE TITLE
Missing Watershed 

### ISSUE THREAD

**Issue by KristianNelson** [IMMM-SFA/teleconnect#15]
Lake Meredith-TX watershed is missing for Amarillo TX. "city_to_intake_mapping.csv" only contains the aquifer associated to Amarillo, not the surface water catchment. Could possibly be other cities where there are watersheds missing.

**Comment by KristianNelson** [comment]
Rogue River watershed is missing for Medford-TX. When run through count_watershed_teleconnections, it returns 0 watersheds for this city.

**Comment by KristianNelson** [comment]
Clifton Forebay and Lewiston Lake watersheds are missing for Bakersfield-CA. When run through count_watershed_teleconnections, it returns 1 watershed for this city, when there are 3 total.

**Comment by KristianNelson** [comment]
@swd-turner All of these missing watersheds (including the Colorado River for Los Angeles) are due to an error in the watershed shapefile where the watershed is not assigned to a specific city, but instead has a name like: "Multiple CA Cities" , "Multiple CO Cities" , "Multiple TX Cities" . "Multiple US Cities"

**Comment by swd-turner** [comment]
@KristianNelson yes this is a major problem actually. Looking back over my script for creating the cities table, I used the intake shape to decipher which cities map to which intakes. Unfortunately, this file defines only one city per intake.... I did correct a number of these cases in instances where I was getting no DVSN_ID for particular cities. But cases like Los Angeles would have been overlooked because it did have DVSN_IDs attached already. Intakes like "Oroville" and "Shasta" should have multiple CA cities, but are connected only to San Diego. Can you take a look at those three UWB files (intakes, cities, watersheds) to see if there's any prospect of dealing with "Multiple CA Cities" and so on ? If not, a painful manual exercise using the UWB website might be required!!

@cdburley thanks for your close attention to the cluster presented earlier this week (the realization of this problem came from your question on LA clustering)

**Comment by KristianNelson** [comment]
@swd-turner It looks like there isn't any way to determine which "multiple city" catchment goes to which city, so I will probably have to extract all the "multiple city" cases into its own table and manually add in the cities...which will be a task. I'll start to make headway on that next week. I don't even think there is a way to list all the cities for each catchment on the website, which would mean I will need to go through all cities for CA, CO, MA, NC to check if they utilize that catchment. There may be a better way to do this, but it will be a difficult task regardless, due to to how the data is set up.

**Comment by swd-turner** [comment]
yea I thought that would be the case. Let's revisit this Monday.
